site_name: SwiftWing S7 Vtol 文档

site_description: SwiftWing S7 Vtol 飞行器用户手册与开发指南
site_author: SwiftWing 团队
site_url: https://swiftwing001.github.io/SwiftWing-S7-Vtol-Tutorial/

theme:
  name: readthedocs

nav:
  - 主页: index.md
  - 产品信息:
    - 免责声明: 0_免责声明.md
    - 产品简介: 1_产品简介.md
    - 物品清单: 2_物品清单.md
    - 硬件规格: 3_硬件规格.md
  - 准备工作:
    - 电池充电: 4_电池充电.md
    - 飞控教程: 5_飞控教程.md
    - 准备通信链路: 6_准备通信链路.md
  - 使用指南:
    - 机载代码介绍: 7_机载代码介绍.md
    - 起飞前地面测试: 8_起飞前地面测试.md
    - 首次飞行: 9_首次飞行.md
  - 功能演示:
    - 绕圆功能Demo: 10_绕圆功能Demo.md
    - 三维导航向量场功能Demo: 11_三维导航向量场功能Demo.md
    - 多项式轨迹demo: 12_多项式轨迹demo.md
  - 维护与资源:
    - 树莓派镜像备份与恢复: 13_镜像备份与恢复.md
    - 资源下载: 14_资源下载.md

# # 本地编译
# mkdocs build
# # 本地预览确认
# mkdocs serve
# # 提交源码到 main 分支
# git add .
# git commit -m "更新内容"
# git push origin master
# # 部署到 GitHub Pages
# mkdocs gh-deploy