site_name: SwiftWing S7 Vtol 文档

site_description: SwiftWing S7 Vtol 飞行器用户手册与开发指南
site_author: SwiftWing 团队
site_url: https://swiftwing001.github.io/SwiftWing-S7-Vtol-Tutorial/

theme:
  name: readthedocs

nav:
  - 主页: index.md
  - 产品介绍:
    - 免责声明: 产品介绍/免责声明.md
    - 产品简介: 产品介绍/产品简介.md
    - 物品清单: 产品介绍/物品清单.md
    - 硬件规格: 产品介绍/硬件规格.md
    - 功能介绍: 产品介绍/功能介绍.md
  - 快速上手:
    - 开箱组装测试: 快速上手/开箱组装测试.md
    - 设备结构检查: 快速上手/设备结构检查.md
    - 飞行场地准备: 快速上手/飞行场地准备.md
    - 电池充电: 快速上手/电池充电.md
    - 遥控器充电: 快速上手/遥控器充电.md
    - 准备遥控器: 快速上手/准备遥控器.md
    - 准备通信链路: 快速上手/准备通信链路.md
    - 飞控教程: 快速上手/飞控教程.md
    - 机载代码介绍: 快速上手/机载代码介绍.md
    - 起飞前地面测试: 快速上手/起飞前地面测试.md
  - 进阶飞行:
    - 手动飞行介绍: 进阶飞行/手动飞行介绍.md
    - 绕圆功能Demo: 进阶飞行/绕圆功能Demo.md
    - 三维导航向量场功能Demo: 进阶飞行/三维导航向量场功能Demo.md
    - 多项式轨迹demo: 进阶飞行/多项式轨迹demo.md
    - 完整飞行演示: 进阶飞行/完整飞行演示.md
    - 硬件二次开发介绍: 进阶飞行/硬件二次开发介绍.md
    - 软件二次开发介绍: 进阶飞行/软件二次开发介绍.md
    - 镜像备份与恢复: 进阶飞行/镜像备份与恢复.md
    - 资源下载: 进阶飞行/资源下载.md
  - 产品维护:
    - 维护保养: 产品维护/维护保养.md

# # 本地编译
# mkdocs build
# # 本地预览确认
# mkdocs serve
# # 提交源码到 main 分支
# git add .
# git commit -m "更新内容"
# git push origin master
# # 部署到 GitHub Pages
# mkdocs gh-deploy